import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const projectRoot = path.resolve(__dirname, '..')
const configPath = path.join(projectRoot, 'invitation.config.json')
const activeThemePath = path.join(projectRoot, 'src', 'common', 'styles', '_active_theme.scss')
const indexPath = path.join(projectRoot, 'index.html')

const defaultTheme = {
    fontPack: 1,
    palette: 2,
    buttonVariant: 'primary',
    menu: {
        variant: 'floating',
        title: 'Menú',
        buttonVariant: 'icon',
    },
    music: {
        variant: 'floating',
        buttonVariant: 'primary',
        songTitle: 'Música de fondo',
        artistName: 'Música del evento',
    },
}

try {
    if (!fs.existsSync(configPath)) {
        console.log('⚠️ invitation.config.json no existe. Creando configuración por defecto...')
        fs.writeFileSync(configPath, JSON.stringify({ theme: defaultTheme, config: {}, sections: {} }, null, 2))
    }

    const configContent = fs.readFileSync(configPath, 'utf8')
    const parsed = JSON.parse(configContent)
    const theme = { ...defaultTheme, ...(parsed.theme || parsed) }

    const fontPack = theme.fontPack || 1
    const palette = theme.palette || 1
    const menuVariant = theme.menu?.variant || theme.menuVariant || 'floating'
    const musicVariant = theme.music?.variant || theme.musicVariant || 'floating'
    const buttonVariant = theme.buttonVariant || 'primary'

    // Título dinámico desde los nombres del Hero o del Menú
    const coupleNames = parsed.sections?.hero?.names || theme.menu?.title || 'Invitación Especial'
    const titleText = `${coupleNames} | Invitación Especial`

    const scssContent = `// ==========================================================================
// AUTO-GENERATED ARCHIVE - DO NOT EDIT DIRECTLY
// Generated by scripts/sync-theme.js based on invitation.config.json
// ==========================================================================

@use './fonts' as font;
@use './palettes' as pal;

// Active Font Pack: Pack ${fontPack}
$font-cursive: font.$font-p${fontPack}-cursive;
$font-serif: font.$font-p${fontPack}-serif;
$font-sans: font.$font-p${fontPack}-sans;

// Active Palette: Palette ${palette}
$color-1: pal.$palette-${palette}-c1;
$color-2: pal.$palette-${palette}-c2;
$color-3: pal.$palette-${palette}-c3;
$color-4: pal.$palette-${palette}-c4;
$color-5: pal.$palette-${palette}-c5;
`

    fs.writeFileSync(activeThemePath, scssContent, 'utf8')

    // Actualizar <title> y meta tags de OpenGraph / Twitter en index.html
    if (fs.existsSync(indexPath)) {
        let indexContent = fs.readFileSync(indexPath, 'utf8')
        indexContent = indexContent.replace(/<title>.*?<\/title>/gi, `<title>${titleText}</title>`)
        indexContent = indexContent.replace(/<meta property="og:title" content=".*?" \/>/gi, `<meta property="og:title" content="${titleText}" />`)
        indexContent = indexContent.replace(/<meta name="twitter:title" content=".*?" \/>/gi, `<meta name="twitter:title" content="${titleText}" />`)
        fs.writeFileSync(indexPath, indexContent, 'utf8')
    }

    console.log(`✅ Tema y Título sincronizados exitosamente desde invitation.config.json: "${titleText}" | Font Pack ${fontPack} | Palette ${palette} | Menu: ${menuVariant} | Music: ${musicVariant}`)
} catch (error) {
    console.error('❌ Error sincronizando el tema:', error)
    process.exit(1)
}
